
import { Student } from '../types';

const generateAcademicDetails = (baseGpa: number) => {
  const subjects = [
    'Data Structures & Algorithms',
    'Computer Organization',
    'Database Management Systems',
    'Software Engineering'
  ];
  return subjects.map(subject => {
    const score = Math.min(100, Math.max(65, Math.floor(baseGpa * 25 + (Math.random() * 10 - 5))));
    let grade = 'B';
    if (score >= 95) grade = 'O'; // Outstanding
    else if (score >= 90) grade = 'A+';
    else if (score >= 80) grade = 'A';
    else if (score >= 70) grade = 'B+';
    else if (score >= 60) grade = 'B';
    else if (score >= 50) grade = 'C';
    return { subject, grade, score };
  });
};

export const MOCK_STUDENTS: Student[] = [
  {
    id: '1',
    name: 'Gulshan Sharma',
    rollNumber: '24R01A6621',
    email: 'alex.j@btech.edu',
    parentName: 'Robert Johnson',
    parentPhone: '9177328305',
    studentPhone: '9177328305',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=alex',
    attendancePercentage: 92,
    gpa: 8.8,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.8)
  },
  {
    id: '2',
    name: 'G.Rohith',
    rollNumber: '24R016622',
    email: 'sarah.m@btech.edu',
    parentName: 'Emily Miller',
    parentPhone: '7780643862',
    studentPhone: '7780643862',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=sarah',
    attendancePercentage: 78,
    gpa: 7.2,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.2)
  },
  {
    id: '3',
    name: 'Kevin Zhang',
    rollNumber: '24R01A6623',
    email: 'kevin.z@btech.edu',
    parentName: 'Li Zhang',
    parentPhone: '+1-202-555-0103',
    studentPhone: '+1-202-555-0177',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=kevin',
    attendancePercentage: 96,
    gpa: 9.2,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.9)
  },
  {
    id: '4',
    name: 'Maria Garcia',
    rollNumber: '24R01A6625',
    email: 'maria.g@btech.edu',
    parentName: 'Carlos Garcia',
    parentPhone: '+1-202-555-0104',
    studentPhone: '+1-202-555-0166',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=maria',
    attendancePercentage: 85,
    gpa: 8.1,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.5)
  },
  {
    id: '5',
    name: 'Sanjana',
    rollNumber: '24R01A6626',
    email: 'james.w@btech.edu',
    parentName: 'Susan Wilson',
    parentPhone: '+1-202-555-0105',
    studentPhone: '+1-202-555-0155',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=james',
    attendancePercentage: 89,
    gpa: 8.4,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.6)
  },
  {
    id: '6',
    name: 'Emma Thompson',
    rollNumber: '24R01A6627',
    email: 'emma.t@btech.edu',
    parentName: 'Mark Thompson',
    parentPhone: '+1-202-555-0106',
    studentPhone: '+1-202-555-0144',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=emma',
    attendancePercentage: 94,
    gpa: 9.5,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.95)
  },
  {
    id: '7',
    name: 'Lucas Brown',
    rollNumber: '24R01A6627',
    email: 'lucas.b@btech.edu',
    parentName: 'Nancy Brown',
    parentPhone: '+1-202-555-0107',
    studentPhone: '+1-202-555-0133',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=lucas',
    attendancePercentage: 82,
    gpa: 7.1,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.1)
  },
  {
    id: '8',
    name: 'Sophia Lee',
    rollNumber: '24R01A6628',
    email: 'sophia.l@btech.edu',
    parentName: 'Daniel Lee',
    parentPhone: '+1-202-555-0108',
    studentPhone: '+1-202-555-0122',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=sophia',
    attendancePercentage: 91,
    gpa: 8.7,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.7)
  },
  {
    id: '9',
    name: 'Khushi Yadav',
    rollNumber: '24R01A6629',
    email: 'noah.p@btech.edu',
    parentName: 'Priya Patel',
    parentPhone: '+1-202-555-0109',
    studentPhone: '+1-202-555-0111',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=noah',
    attendancePercentage: 88,
    gpa: 7.8,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.4)
  },
  {
    id: '10',
    name: 'Vaishnavi',
    rollNumber: '24R01A6630',
    email: 'mia.k@btech.edu',
    parentName: 'Jun Kim',
    parentPhone: '+1-202-555-0110',
    studentPhone: '+1-202-555-0100',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=mia',
    attendancePercentage: 97,
    gpa: 9.8,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(4.0)
  },
  {
    id: '11',
    name: 'Samiksha',
    rollNumber: '24R01A6631',
    email: 'ethan.d@btech.edu',
    parentName: 'Mary Davis',
    parentPhone: '+1-202-555-0201',
    studentPhone: '+1-202-555-0211',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=ethan',
    attendancePercentage: 86,
    gpa: 7.5,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.3)
  },
  {
    id: '12',
    name: 'Satya',
    rollNumber: '24R01A6632',
    email: 'ava.w@btech.edu',
    parentName: 'George Williams',
    parentPhone: '+1-202-555-0202',
    studentPhone: '+1-202-555-0222',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=ava',
    attendancePercentage: 90,
    gpa: 8.5,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.75)
  },
  {
    id: '13',
    name: 'Ishan',
    rollNumber: '24R01A6633',
    email: 'liam.m@btech.edu',
    parentName: 'Rosa Martinez',
    parentPhone: '+1-202-555-0203',
    studentPhone: '+1-202-555-0233',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=liam',
    attendancePercentage: 84,
    gpa: 7.4,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.2)
  },
  {
    id: '14',
    name: 'Isabella Taylor',
    rollNumber: '24R01A6634',
    email: 'isabella.t@btech.edu',
    parentName: 'John Taylor',
    parentPhone: '+1-202-555-0204',
    studentPhone: '+1-202-555-0244',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=isabella',
    attendancePercentage: 93,
    gpa: 8.9,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.85)
  },
  {
    id: '15',
    name: 'Oliver Anderson',
    rollNumber: '24R01A6636',
    email: 'oliver.a@btech.edu',
    parentName: 'Patricia Anderson',
    parentPhone: '+1-202-555-0205',
    studentPhone: '+1-202-555-0255',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=oliver',
    attendancePercentage: 81,
    gpa: 6.9,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(2.9)
  },
  {
    id: '16',
    name: 'Hrishikesh',
    rollNumber: '24R01A6637',
    email: 'charlotte.m@btech.edu',
    parentName: 'Robert Moore',
    parentPhone: '+1-202-555-0206',
    studentPhone: '+1-202-555-0266',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=charlotte',
    attendancePercentage: 95,
    gpa: 9.3,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.9)
  },
  {
    id: '17',
    name: 'Junaid Pasha',
    rollNumber: '24R01A6639',
    email: 'william.t@btech.edu',
    parentName: 'Betty Thomas',
    parentPhone: '+1-202-555-0207',
    studentPhone: '+1-202-555-0277',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=william',
    attendancePercentage: 87,
    gpa: 7.9,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.45)
  },
  {
    id: '18',
    name: 'Saif Patel',
    rollNumber: '24R01A6640',
    email: 'amara.o@btech.edu',
    parentName: 'Ike Okafor',
    parentPhone: '+1-202-555-0208',
    studentPhone: '+1-202-555-0288',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=amara',
    attendancePercentage: 98,
    gpa: 9.9,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(4.0)
  },
  {
    id: '19',
    name: 'Hiroshi Tanaka',
    rollNumber: '24R01A6641',
    email: 'hiroshi.t@btech.edu',
    parentName: 'Kenji Tanaka',
    parentPhone: '+1-202-555-0209',
    studentPhone: '+1-202-555-0299',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=hiroshi',
    attendancePercentage: 91,
    gpa: 9.1,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.8)
  },
  {
    id: '20',
    name: 'Elena Rossi',
    rollNumber: '24R01A6642',
    email: 'elena.r@btech.edu',
    parentName: 'Luca Rossi',
    parentPhone: '+1-202-555-0300',
    studentPhone: '+1-202-555-0310',
    grade: 'B.Tech II Year',
    section: 'CSM-A',
    avatar: 'https://i.pravatar.cc/150?u=elena',
    attendancePercentage: 83,
    gpa: 7.0,
    attendanceHistory: [],
    academicDetails: generateAcademicDetails(3.0)
  }
];
